stages:
  - linting
  - test

flake8:
    stage: linting
    image: registry.gitlab.com/pipeline-components/flake8:latest
    script:
      - pip install -r requirements/test.txt
      - flake8 --verbose .

black:
    stage: linting
    image: registry.gitlab.com/pipeline-components/black:latest
    script:
      - black --verbose .

unit-test-job:
  stage: test
  image: python:3.12
  script:
    - python -m venv .venv
    - source .venv/bin/activate
    - python -m pip install -r requirements/dev.txt -r requirements/prod.txt
    - cp .env.example .env
    - cd lyceum
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test
    - deactivate
