stages:
  - linting
  - test

flake8:
    stage: linting
    image: registry.gitlab.com/pipeline-components/flake8:latest
    script:
        - flake8 --verbose .

black:
    stage: linting
    image: registry.gitlab.com/pipeline-components/black:latest
    script:
        - black --check .

unit-test-job:
  stage: test
  image: python:3.12
  script:
    - python -m venv .venv
    - source .venv/bin/activate
    - python -m pip install -r requirements/dev.txt -r requirements/prod.txt
    - cd lyceum
    - python manage.py test
    - deactivate
