# Generated by Django 4.2 on 2024-03-15 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="напишите текст сообщения",
                        verbose_name="текст",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="дата и время создания",
                        null=True,
                        verbose_name="создано",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Получено", "Received"),
                            ("В обработке", "Processing"),
                            ("Ответ дан", "Answer"),
                        ],
                        default="Получено",
                        max_length=11,
                        verbose_name="статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "обратная связь",
                "verbose_name_plural": "обратные связи",
            },
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания",
                        null=True,
                        verbose_name="создано",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("Получено", "Received"),
                            ("В обработке", "Processing"),
                            ("Ответ дан", "Answer"),
                        ],
                        db_column="from",
                        help_text="Статус",
                        max_length=100,
                        null=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "to",
                    models.CharField(
                        choices=[
                            ("Получено", "Received"),
                            ("В обработке", "Processing"),
                            ("Ответ дан", "Answer"),
                        ],
                        db_column="to",
                        help_text="Статус",
                        max_length=100,
                        null=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedbackFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=feedback.models.FeedbackFile.upload_to
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        help_text="файлы",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        related_query_name="files",
                        to="feedback.feedback",
                        verbose_name="обратная связь",
                    ),
                ),
            ],
            options={
                "verbose_name": "файлы обратной связи",
                "verbose_name_plural": "файлы обратных связей",
            },
        ),
        migrations.CreateModel(
            name="FeedbackAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="напишите имя",
                        max_length=150,
                        null=True,
                        verbose_name="имя",
                    ),
                ),
                (
                    "mail",
                    models.EmailField(
                        help_text="почтовый адрес",
                        max_length=254,
                        verbose_name="почта",
                    ),
                ),
                (
                    "feedback",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author",
                        related_query_name="author",
                        to="feedback.feedback",
                    ),
                ),
            ],
            options={
                "verbose_name": "данные автора",
                "verbose_name_plural": "данные авторов",
            },
        ),
    ]
