# Generated by Django 4.2 on 2024-03-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                help_text="Напишите своё имя",
                max_length=100,
                null=True,
                verbose_name="имя",
            ),
        ),
    ]
