# Generated by Django 4.2.9 on 2024-03-15 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statuslog",
            options={
                "verbose_name": "журнал состояния",
                "verbose_name_plural": "журнал состояний",
            },
        ),
        migrations.AddField(
            model_name="statuslog",
            name="feedback",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feedback.feedback",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("Получено", "Received"),
                    ("В обработке", "Processing"),
                    ("Ответ дан", "Answer"),
                ],
                db_column="from",
                max_length=11,
                null=True,
                verbose_name="с",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="дата и время создания",
                null=True,
                verbose_name="создано",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="to",
            field=models.CharField(
                choices=[
                    ("Получено", "Received"),
                    ("В обработке", "Processing"),
                    ("Ответ дан", "Answer"),
                ],
                max_length=11,
                null=True,
                verbose_name="на",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
