# Generated by Django 4.2.9 on 2024-03-28 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "feedback",
            "0002_alter_statuslog_options_statuslog_feedback_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("Получено", "Received"),
                    ("В обработке", "Processing"),
                    ("Ответ дан", "Answer"),
                ],
                default="Получено",
                help_text="Статус",
                max_length=11,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackauthor",
            name="feedback",
            field=models.OneToOneField(
                help_text="Обратная связь",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                related_query_name="author",
                to="feedback.feedback",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackfile",
            name="file",
            field=models.FileField(
                help_text="Файлы",
                upload_to=feedback.models.FeedbackFile.upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="feedback",
            field=models.ForeignKey(
                help_text="Обратная связь",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feedback.feedback",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("Получено", "Received"),
                    ("В обработке", "Processing"),
                    ("Ответ дан", "Answer"),
                ],
                db_column="from",
                help_text="с",
                max_length=11,
                null=True,
                verbose_name="с",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="to",
            field=models.CharField(
                choices=[
                    ("Получено", "Received"),
                    ("В обработке", "Processing"),
                    ("Ответ дан", "Answer"),
                ],
                help_text="на",
                max_length=11,
                null=True,
                verbose_name="на",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="user",
            field=models.ForeignKey(
                help_text="Пользователь",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
