# Generated by Django 4.2 on 2024-03-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_feedback_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                help_text="Статус",
                max_length=100,
                null=True,
                verbose_name="status",
            ),
        ),
    ]
