# Generated by Django 4.2 on 2024-03-14 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0003_feedback_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "обратная связь",
                "verbose_name_plural": "обратные связи",
            },
        ),
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Напишите своё имя",
                max_length=100,
                null=True,
                verbose_name="имя",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("Получено", "Received"),
                    ("В обработке", "Processing"),
                    ("Ответ дан", "Answer"),
                ],
                default="Получено",
                help_text="Статус",
                max_length=100,
                verbose_name="status",
            ),
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания",
                        null=True,
                        verbose_name="создано",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("Получено", "Received"),
                            ("В обработке", "Processing"),
                            ("Ответ дан", "Answer"),
                        ],
                        db_column="from",
                        help_text="Статус",
                        max_length=100,
                        null=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("Получено", "Received"),
                            ("В обработке", "Processing"),
                            ("Ответ дан", "Answer"),
                        ],
                        db_column="to",
                        help_text="Статус",
                        max_length=100,
                        null=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
        ),
    ]
