# Generated by Django 4.2 on 2024-03-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback",
            "0004_alter_feedback_options_alter_feedback_name_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="statuslog",
            old_name="to_status",
            new_name="to",
        ),
    ]
