# Generated by Django 4.2.9 on 2024-03-22 13:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, null=True, verbose_name="Биография"
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        help_text="Введите дату рождения пользователя",
                        null=True,
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "coffee_count",
                    models.IntegerField(
                        default=0,
                        help_text="Количество переходов по /coffee/",
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                        verbose_name="Сколько раз пользователь пил кофе",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        help_text="Аватар пользователя",
                        null=True,
                        upload_to=users.models.Profile.image_path,
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Дополнительное поле",
                "verbose_name_plural": "Дополнительные поля",
            },
        ),
    ]
