# Generated by Django 4.2.9 on 2024-03-22 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="coffee_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Количество переходов по /coffee/",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Сколько раз пользователь пил кофе",
            ),
        ),
    ]
