# Generated by Django 4.2.9 on 2024-03-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="coffee_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="сколько раз пользователь пытался сварить кофе ",
                verbose_name="количество переходов по /coffee/",
            ),
        ),
    ]
