# Generated by Django 4.2.9 on 2024-03-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0013_alter_user_email"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
        ),
    ]
