# Generated by Django 4.2.9 on 2024-03-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_coffe_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="coffe_count",
            new_name="coffee_count",
        ),
    ]
