# Generated by Django 4.2.9 on 2024-03-25 17:53

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_coffee_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.AddField(
            model_name="profile",
            name="attempts_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Попытки входа"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="block_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата блокировки"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="coffee_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Количество переходов по /coffee/",
                verbose_name="Сколько раз пользователь пил кофе",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите автарку",
                null=True,
                upload_to=users.models.Profile.image_path,
                verbose_name="аватарка",
            ),
        ),
    ]
