# Generated by Django 4.2.9 on 2024-03-28 18:56

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_profile_bio_profile_attempts_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="attempts_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Попытки входа",
                verbose_name="Попытки входа",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="block_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата блокировки",
                null=True,
                verbose_name="Дата блокировки",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите автарку",
                null=True,
                upload_to=users.models.Profile.image_path,
                verbose_name="Аватарка",
            ),
        ),
    ]
