# Generated by Django 4.2.9 on 2024-03-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={
                "verbose_name": "оценка",
                "verbose_name_plural": "оценки",
            },
        ),
    ]
