# Generated by Django 4.2.9 on 2024-03-26 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_profile_bio_profile_attempts_count_and_more"),
        ("rating", "0002_alter_rating_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
                verbose_name="пользователь",
            ),
        ),
    ]
