# Generated by Django 4.2.9 on 2024-03-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0003_alter_rating_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
