# Generated by Django 4.2.9 on 2024-03-27 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_itemmainimage_image_and_more"),
        ("rating", "0003_alter_rating_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="rating",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating",
                related_query_name="rating",
                to="catalog.item",
                verbose_name="товар",
            ),
        ),
    ]
