# Generated by Django 4.2.9 on 2024-03-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0004_rating_updated_alter_rating_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={
                "default_related_name": "rating",
                "ordering": ("-updated",),
                "verbose_name": "оценка",
                "verbose_name_plural": "оценки",
            },
        ),
    ]
