# Generated by Django 4.2.9 on 2024-03-29 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0011_alter_category_is_published_alter_category_slug_and_more",
        ),
        ("users", "0004_alter_profile_attempts_count_and_more"),
        ("rating", "0005_alter_rating_options_alter_rating_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating",
                related_query_name="rating",
                to="catalog.item",
                verbose_name="товар",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Ненависть"),
                    (2, "Неприязнь"),
                    (3, "Нейтрально"),
                    (4, "Обожание"),
                    (5, "Любовь"),
                ],
                null=True,
                verbose_name="оценка",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="rating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
                verbose_name="пользователь",
            ),
        ),
    ]
