# Generated by Django 4.2 on 2024-02-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                related_name="tags",
                to="catalog.tag",
                verbose_name="Теги",
            ),
        ),
    ]
