# Generated by Django 4.2 on 2024-02-29 14:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        verbose_name="опубликовано",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="max 150 символов",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Описание должно быть больше, чем из 2х слов"
                        " и содержать слова 'превосходно, роскошно'",
                        validators=[
                            catalog.validators.ValidateMustContain(
                                "превосходно",
                                "роскошно",
                            ),
                            django.core.validators.MinLengthValidator(2),
                        ],
                        verbose_name="текст",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Выберите категорию",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.category",
                        verbose_name="категория",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        help_text="Удерживайте 'Control' (или 'Command' на"
                        " Mac), чтобы выбрать несколько значений",
                        related_name="tags",
                        to="catalog.tag",
                        verbose_name="тег",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
                "db_table": "catalog_item",
            },
        ),
    ]
