# Generated by Django 4.2 on 2024-02-29 14:16

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemSecondaryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    sorl.thumbnail.fields.ImageField(
                        help_text="Будет приведено к ширине 1280px",
                        upload_to="catalog/items/",
                        verbose_name="картинка",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "дополнительное изображение",
                "verbose_name_plural": "дополнительные изображения",
            },
        ),
        migrations.CreateModel(
            name="ItemMainImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    sorl.thumbnail.fields.ImageField(
                        help_text="Будет приведено к ширине 1280px",
                        upload_to="catalog/items/",
                        verbose_name="картинка",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_image",
                        to="catalog.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "главное изображение",
                "verbose_name_plural": "главные изображения",
            },
        ),
    ]
