# Generated by Django 4.2 on 2024-02-29 15:58

import django.core.validators
from django.db import migrations
import mdeditor.fields

import catalog.validators

__all__ = [
    "Migration",
]


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_itemsecondaryimage_itemmainimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=mdeditor.fields.MDTextField(
                help_text="Описание должно быть больше, чем из 2х слов"
                " и содержать слова 'превосходно, роскошно'",
                validators=[
                    catalog.validators.ValidateMustContain(
                        "превосходно",
                        "роскошно",
                    ),
                    django.core.validators.MinLengthValidator(2),
                ],
                verbose_name="текст",
            ),
        ),
    ]
