# Generated by Django 4.2 on 2024-02-19 16:26

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_category_options_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="max 150 символов",
                max_length=150,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Выберите категорию",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                help_text="max 150 символов",
                max_length=150,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                help_text="Удерживайте 'Control' (или 'Command' на"
                " Mac), чтобы выбрать несколько значений",
                related_name="tags",
                to="catalog.tag",
                verbose_name="Тег",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Описание должно быть больше, чем из 2х слов "
                "и содержать слова 'превосходно, роскошно'",
                validators=[
                    catalog.models.perfect_in_text_validator,
                    django.core.validators.MinValueValidator(2),
                ],
                verbose_name="Текст",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="max 150 символов",
                max_length=150,
                verbose_name="Название",
            ),
        ),
    ]
