# Generated by Django 4.2 on 2024-02-28 19:55

import django.core.validators
from django.db import migrations, models

import catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_itemsecondaryimage_itemmainimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                help_text="Удерживайте 'Control' (или 'Command' на Mac), "
                "чтобы выбрать несколько значений",
                related_name="tags",
                to="catalog.tag",
                verbose_name="тег",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Описание должно быть больше, чем из 2х слов"
                " и содержать слова 'превосходно, роскошно'",
                validators=[
                    catalog.validators.ValidateMustContain(
                        "превосходно",
                        "роскошно",
                    ),
                    django.core.validators.MinLengthValidator(2),
                ],
                verbose_name="текст",
            ),
        ),
    ]
