# Generated by Django 4.2 on 2024-02-19 18:59

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_category_name_alter_item_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Описание должно быть больше, чем из 2х слов "
                "и содержать слова 'превосходно, роскошно'",
                validators=[
                    catalog.models.perfect_in_text_validator,
                    django.core.validators.MinLengthValidator(2),
                ],
                verbose_name="Текст",
            ),
        ),
    ]
