# Generated by Django 4.2 on 2024-03-05 16:45

from django.db import migrations, models
import sorl.thumbnail.fields

__all__ = [
    "Migration",
]


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_item_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False,
                verbose_name="на главной странице",
            ),
        ),
        migrations.AlterField(
            model_name="itemmainimage",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                help_text="Будет приведено к 300x300",
                upload_to="catalog/items//%Y/%m/%d",
                verbose_name="картинка",
            ),
        ),
        migrations.AlterField(
            model_name="itemsecondaryimage",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                help_text="Будет приведено к 300x300",
                upload_to="catalog/items//%Y/%m/%d",
                verbose_name="картинка",
            ),
        ),
    ]
