# Generated by Django 4.2 on 2024-02-20 16:18

import django.core.validators
from django.db import migrations, models

import catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_item_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                max_length=200,
                unique=True,
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.IntegerField(
                default=100,
                validators=[
                    django.core.validators.MaxValueValidator(32767),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Вес",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Описание должно быть больше, чем из 2х "
                "слов и содержать слова 'превосходно, роскошно'",
                validators=[
                    catalog.validators.ValidateMustContain(
                        "превосходно",
                        "роскошно",
                    ),
                    django.core.validators.MinLengthValidator(2),
                ],
                verbose_name="Текст",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                max_length=200,
                unique=True,
                verbose_name="Слаг",
            ),
        ),
    ]
