# Generated by Django 4.2 on 2024-03-05 21:11

from django.db import migrations, models
import django.db.models.deletion

__all__ = [
    "Migration",
]


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_item_is_on_main_alter_itemmainimage_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmainimage",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_image",
                related_query_name="main_image",
                to="catalog.item",
            ),
        ),
        migrations.AlterField(
            model_name="itemsecondaryimage",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                related_query_name="images",
                to="catalog.item",
            ),
        ),
    ]
