# Generated by Django 4.2 on 2024-03-07 15:11

from django.db import migrations, models

__all__ = [
    "Migration",
]


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_itemmainimage_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="change_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="item",
            name="create_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
