# Generated by Django 4.2 on 2024-03-07 20:25

from django.db import migrations, models

__all__ = [
    "Migration",
]


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_itemmainimage_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
