# Generated by Django 4.2.9 on 2024-03-15 18:04

import core.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_item_created_item_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmainimage",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                upload_to=core.models.get_path_image,
                verbose_name="изображение",
            ),
        ),
        migrations.AlterField(
            model_name="itemsecondaryimage",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                upload_to=core.models.get_path_image,
                verbose_name="изображение",
            ),
        ),
    ]
