# Generated by Django 4.2.9 on 2024-03-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_itemmainimage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                help_text="Нормализованное название элемента",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="нормализованное название",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                help_text="Нормализованное название элемента",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="нормализованное название",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                help_text="Нормализованное название элемента",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="нормализованное название",
            ),
        ),
    ]
