# Generated by Django 4.2.9 on 2024-03-28 18:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0010_item_normalized_name_alter_category_normalized_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Опубликовано",
                verbose_name="опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Slug",
                max_length=200,
                unique=True,
                verbose_name="слаг",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.IntegerField(
                default=100,
                help_text="Вес",
                validators=[
                    django.core.validators.MaxValueValidator(32767),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="вес",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Время создания", null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False,
                help_text="Товары, расположенные на главной странице",
                verbose_name="на главной странице",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Опубликовано",
                verbose_name="опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, help_text="Время обновления", null=True
            ),
        ),
        migrations.AlterField(
            model_name="itemmainimage",
            name="item",
            field=models.OneToOneField(
                help_text="Главное изображение",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_image",
                related_query_name="main_image",
                to="catalog.item",
            ),
        ),
        migrations.AlterField(
            model_name="itemsecondaryimage",
            name="item",
            field=models.ForeignKey(
                help_text="Дополнительное изображение",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                related_query_name="images",
                to="catalog.item",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Опубликовано",
                verbose_name="опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="Slug",
                max_length=200,
                unique=True,
                verbose_name="слаг",
            ),
        ),
    ]
